# -*- coding: utf-8 -*-
"""Literal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179xQfPeUzDpUfhk-IeqBdm5xbgZEX0rm

# **Literals**
"""

# 1 numerical Literals
a = 0b1010 #Binary Literials
b = 100 #Decimal Literal
c = 0o310 #Octal Literal
d = 0x12c #Hexadecimal Literal
print(a,b,c,d)

# floot Literal
float_1 = 10.5
float_2 = 1.5e2
float_3 = 1.5e-3
print(float_1, float_2, float_3)

# complex
x = 3.14J
print(x, x.imag, x.real)

# 2 string Literals

Single_string = 'hello World'
double_string = "This is Python"
Three_string  = '''This is Python'''
Mul_string    = """This is Python"""
unicode = u"\u0001f600"
raw_str = r"raw \n string"
print(Single_string)
print(double_string)
print(Three_string)
print(Mul_string)
print(unicode)
print(raw_str)

# 3 boolen literal
a = True + 4
b = False + 10
print("a:", a)
print("b:", b)

# special literal
a = None
print(a)



