# -*- coding: utf-8 -*-
"""PRINT FUNCATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLbvOCQ0PBYnbW4vQq6lEXK3-fzJyD3m
"""

print('hello world')

print(6)

print(5.6)

print(False)

print("India", "pakistan", "nepal")

print("India", "pakistan", "nepal", sep='/')

print("India", "pakistan", "nepal", sep='-')

print('hello')
print('world')

print('hello', end=' ')
print('world')

a=10
b=20
a
b

a=10
b=20
a
b

a=10
b=20
print(a)
print(b)

print(10)
print(10,20)
print('python')
print(10,20,'python')

num1=20
num2=30
add=num1+num2
print(add)

#print result with string

num1=20
num2=30
add=num1+num2
print('The addition of',num1,'and',num2,'is=',add)

name='Python'
age=20
city='hyd'
#hellow my name is python and i am 10 year old from hydrabad

print('My name is',name,'and i am',age,'years old form',city)

num1=20
num2=30
add=num1+num2
print('The addition of {} and {} is= {}'.format(num1,num2,add))

name='Python'
age=20
city='hyd'

print('hello my name is {}, and i am {} years old from {} '.format(name,age,city))

num1=100
num2=25
num3=333
num1=20
num2=30
avg=(num1+num2+num3)/3 # or we can use avg=round(num1+num2+num3)/3,2)
avg1=round((num1+num2+num3)/3,2)
# The avrage of num1,num2,num3 is = avg
print('The avrage of {}, {}, and {} is= {} or {}'.format(num1,num2,num3,
avg,avg1)) # here we can use round(avg,2) also
#The avrage of 100, 25, and 333 is= 152.66666666666666 or 152.67

num1=20
num2=30
add=num1+num2
print(f'The addition of {num1} and {num2} is= {add}') # alwase prefer this

name='Python'
age=20
city='hyd'
#hellow my name is python and i am 10 year old from hydrabad

print(f'hello my name is {name}, and i am {age} year old, from {city}.')

num1=100
num2=25
num3=333
avg=round((num1+num2+num3)/3,2) # or we can use avg=round(num1+num2+num3)/3,2)
# The avrage of num1,num2,num3 is = avg

print(f'The avrage of {num1}, {num2} and {num3} is = {avg}')

# lete combine all
num1=10
num2=20
add = num1+ num2
print('The addition of',num1,'and',num2,'is=',add)
print('The addition of {} and {} is= {}'.format(num1,num2,add))
print(f'The addition of {num1} and {num2} is= {add}')

# end statement

print('hello') # 1st statement
print('good moorning') # 2nd statement)
# i want print like:- hellow good morning

print('hello', end=' ') # 1st statement
print('world good day') # 2nd statement

#seprator

print('hello','hai','how are you',sep='--->')

print('hello','hai','how are you',sep='&')

print('hello','hai','how are you',sep='@')

print('hello','hai','how are you',sep=' ')

print(3,'.') # . is far from 3 so here we will use sep method

print(3,'.',sep='') # see now space setteld(also use to remove space B/W words)

print(1,2,end=' ')
print(3,'.',sep='')
# will print 1 2 3.

